image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - Pivotal.vscode-boot-dev-pack@0.0.8:KGahbNlLCY19QUebUzdLbA==
    - Pivotal.vscode-spring-boot@1.23.0:1iLvjTfznJrV611qRUeOHg==
    - vscjava.vscode-spring-boot-dashboard@0.1.10:aUqbvdDhzcEQa2kKi5PEZg==
    - vscjava.vscode-maven@0.21.2:tFEkt2FqLujaNTLU5AmRiQ==
    - cool2k.vscode-lombok@1.0.2:e816/wZO588Jp8PN58Wj6g==