image:
  file: .gitpod.Dockerfile

tasks:
  - init: ./mvnw clean install
    command: ./mvnw spring-boot:run 

vscode:
  extensions:
    - Pivotal.vscode-boot-dev-pack@0.0.8:KGahbNlLCY19QUebUzdLbA==
    - Pivotal.vscode-spring-boot@1.23.0:1iLvjTfznJrV611qRUeOHg==
    - vscjava.vscode-spring-boot-dashboard@0.1.10:aUqbvdDhzcEQa2kKi5PEZg==